name: Hello GitHub Actions - Conditional

on:
  push:
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello Conditional
      run: echo "Hello, GitHub Actions! (Conditional)"
