name: Use Secret Example

on: [push]

jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch User Data from GitHub API
      run: |
        curl -H "Authorization: Bearer ${{ secrets.MY_API_TOKEN }}" \
        https://api.github.com/user
